apiVersion: v1
kind: Secret
metadata:
  name: goserver-secret
type: Opaque
data:
# echo "marcus" | base64
  USER: bWFyY3VzCg==
  PASSWORD: MTIzNDU2Cg==
# This file shouldn't be on github.. just a example